name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: TestForest Dashboard
  # You may pin to the exact commit or the version.
  # uses: test-summary/action@fee35d7df20790255fe6aa92cf0f6d28092ecf2f
      uses: test-summary/action@v2.2
      with:
    # Path(s) to test output file(s) to analyze
        paths: | 
          target/surefire-reports/*.xml
    # File to write with rendered output
        output: summary.html
    # Types of tests to show in the results table
        show: failed, skipped, passed
          

    - name: Run Tests
      run: mvn test
